import { BookOpenCheck, BrainCircuit, CalendarHeart, ChefHat, Dumbbell, GraduationCap, Infinity, Languages, Lightbulb, Newspaper, NotebookPen, Palette, RefreshCcw } from "lucide-react";

export const projectRegistry = [
  {
    name: "Portfolio Raja",
    label: "Project portal",
    status: "Running on localhost:8085",
    href: "/",
    external: false,
    icon: Infinity,
    tone: "bg-[#fdaa3e]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja",
  },
  {
    name: "JagsRajKitchen",
    label: "Restaurant site",
    status: "Running on localhost:8086",
    href: "http://localhost:8086/",
    external: true,
    icon: ChefHat,
    tone: "bg-[#5c6b3a]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/jagsrajkitchen",
  },
  {
    name: "AI Learn Raja",
    label: "Learning app",
    status: "Running on localhost:8087",
    href: "http://localhost:8087/",
    external: true,
    icon: BrainCircuit,
    tone: "bg-[#3f6ea5]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/ailearnraja",
  },
  {
    name: "Forma Fitness",
    label: "Fitness app",
    status: "Running on localhost:8088",
    href: "https://formafitness-nine.vercel.app/",
    external: true,
    icon: Dumbbell,
    tone: "bg-[#8a6bb3]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/forma-fitness",
  },
  {
    name: "GenZ Style Learn",
    label: "Style learning app",
    status: "Running on localhost:8089",
    href: "http://localhost:8089/",
    external: true,
    icon: Palette,
    tone: "bg-[#c45f8c]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/genzstylelearn",
  },
  {
    name: "Reset Mind",
    label: "Mind reset app",
    status: "Running on localhost:8091",
    href: "http://localhost:8091/",
    external: true,
    icon: RefreshCcw,
    tone: "bg-[#1f7a78]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/resetmindproj",
  },
  {
    name: "ABC Notes",
    label: "Notes and folders",
    status: "Live on Vercel",
    href: "https://apple-notes-clone-pi.vercel.app/",
    external: true,
    icon: NotebookPen,
    tone: "bg-[#d89b28]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/apple-notes-clone",
  },
  {
    name: "AI Ascend Academy",
    label: "Learning academy",
    status: "Running on localhost:8093",
    href: "http://localhost:8093/",
    external: true,
    icon: BookOpenCheck,
    tone: "bg-[#4b6fbf]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/ai-ascend-academy",
  },
  {
    name: "Capture Thoughts",
    label: "Thought capture app",
    status: "Running on localhost:8094",
    href: "https://capturethoughts.vercel.app/",
    external: true,
    icon: Lightbulb,
    tone: "bg-[#b45a6f]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/capture-thoughts",
  },
  {
    name: "Guide Learn AI",
    label: "AI learning guide",
    status: "Running on localhost:8095",
    href: "https://guide-learn-ai.vercel.app/",
    external: true,
    icon: GraduationCap,
    tone: "bg-[#2f7c9d]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/guide-learn-ai",
  },
  {
    name: "Speak Practice Tamil",
    label: "Tamil speaking practice",
    status: "Running on localhost:8096",
    href: "https://tamilpracticespeak.vercel.app/",
    external: true,
    icon: Languages,
    tone: "bg-[#8d4eb8]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/speakpracticetamil",
  },
  {
    name: "Desi Events",
    label: "Events app",
    status: "Running on localhost:8097",
    href: "http://localhost:8097/",
    external: true,
    icon: CalendarHeart,
    tone: "bg-[#c66b32]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/desievents",
  },
  {
    name: "Tech Blog Raja",
    label: "Tech blog",
    status: "Running on localhost:8098",
    href: "http://localhost:8098/",
    external: true,
    icon: Newspaper,
    tone: "bg-[#5262b8]",
    path: "/Users/rajav/Documents/Coding/CGPT-help/portfolioraja/apps/techblograja",
  },
] as const;
