/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellTailorRouteImport } from './routes/_shell.tailor'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellPipelineRouteImport } from './routes/_shell.pipeline'
import { Route as ShellFollowUpsRouteImport } from './routes/_shell.follow-ups'
import { Route as ShellFocusRouteImport } from './routes/_shell.focus'
import { Route as ShellApplicationsRouteImport } from './routes/_shell.applications'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTailorRoute = ShellTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelineRoute = ShellPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFollowUpsRoute = ShellFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFocusRoute = ShellFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApplicationsRoute = ShellApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/applications': typeof ShellApplicationsRoute
  '/focus': typeof ShellFocusRoute
  '/follow-ups': typeof ShellFollowUpsRoute
  '/pipeline': typeof ShellPipelineRoute
  '/profile': typeof ShellProfileRoute
  '/tailor': typeof ShellTailorRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof ShellAnalyticsRoute
  '/applications': typeof ShellApplicationsRoute
  '/focus': typeof ShellFocusRoute
  '/follow-ups': typeof ShellFollowUpsRoute
  '/pipeline': typeof ShellPipelineRoute
  '/profile': typeof ShellProfileRoute
  '/tailor': typeof ShellTailorRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/applications': typeof ShellApplicationsRoute
  '/_shell/focus': typeof ShellFocusRoute
  '/_shell/follow-ups': typeof ShellFollowUpsRoute
  '/_shell/pipeline': typeof ShellPipelineRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/tailor': typeof ShellTailorRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/applications'
    | '/focus'
    | '/follow-ups'
    | '/pipeline'
    | '/profile'
    | '/tailor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/applications'
    | '/focus'
    | '/follow-ups'
    | '/pipeline'
    | '/profile'
    | '/tailor'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/applications'
    | '/_shell/focus'
    | '/_shell/follow-ups'
    | '/_shell/pipeline'
    | '/_shell/profile'
    | '/_shell/tailor'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tailor': {
      id: '/_shell/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof ShellTailorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipeline': {
      id: '/_shell/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof ShellPipelineRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/follow-ups': {
      id: '/_shell/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof ShellFollowUpsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/focus': {
      id: '/_shell/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof ShellFocusRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/applications': {
      id: '/_shell/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ShellApplicationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellApplicationsRoute: typeof ShellApplicationsRoute
  ShellFocusRoute: typeof ShellFocusRoute
  ShellFollowUpsRoute: typeof ShellFollowUpsRoute
  ShellPipelineRoute: typeof ShellPipelineRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellTailorRoute: typeof ShellTailorRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellApplicationsRoute: ShellApplicationsRoute,
  ShellFocusRoute: ShellFocusRoute,
  ShellFollowUpsRoute: ShellFollowUpsRoute,
  ShellPipelineRoute: ShellPipelineRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellTailorRoute: ShellTailorRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
