/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as ShadowingRouteImport } from './routes/shadowing'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MarathonRouteImport } from './routes/marathon'
import { Route as EchoRouteImport } from './routes/echo'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AiRoomRouteImport } from './routes/ai-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenesIndexRouteImport } from './routes/scenes.index'
import { Route as ScenesSceneRouteImport } from './routes/scenes.$scene'

const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingRoute = ShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonRoute = MarathonRouteImport.update({
  id: '/marathon',
  path: '/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoRoute = EchoRouteImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoomRoute = AiRoomRouteImport.update({
  id: '/ai-room',
  path: '/ai-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesIndexRoute = ScenesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScenesRoute,
} as any)
const ScenesSceneRoute = ScenesSceneRouteImport.update({
  id: '/$scene',
  path: '/$scene',
  getParentRoute: () => ScenesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-room': typeof AiRoomRoute
  '/daily': typeof DailyRoute
  '/echo': typeof EchoRoute
  '/marathon': typeof MarathonRoute
  '/progress': typeof ProgressRoute
  '/scenes': typeof ScenesRouteWithChildren
  '/shadowing': typeof ShadowingRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak': typeof SpeakRoute
  '/scenes/$scene': typeof ScenesSceneRoute
  '/scenes/': typeof ScenesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-room': typeof AiRoomRoute
  '/daily': typeof DailyRoute
  '/echo': typeof EchoRoute
  '/marathon': typeof MarathonRoute
  '/progress': typeof ProgressRoute
  '/shadowing': typeof ShadowingRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak': typeof SpeakRoute
  '/scenes/$scene': typeof ScenesSceneRoute
  '/scenes': typeof ScenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-room': typeof AiRoomRoute
  '/daily': typeof DailyRoute
  '/echo': typeof EchoRoute
  '/marathon': typeof MarathonRoute
  '/progress': typeof ProgressRoute
  '/scenes': typeof ScenesRouteWithChildren
  '/shadowing': typeof ShadowingRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak': typeof SpeakRoute
  '/scenes/$scene': typeof ScenesSceneRoute
  '/scenes/': typeof ScenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-room'
    | '/daily'
    | '/echo'
    | '/marathon'
    | '/progress'
    | '/scenes'
    | '/shadowing'
    | '/shorts'
    | '/sitemap.xml'
    | '/speak'
    | '/scenes/$scene'
    | '/scenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-room'
    | '/daily'
    | '/echo'
    | '/marathon'
    | '/progress'
    | '/shadowing'
    | '/shorts'
    | '/sitemap.xml'
    | '/speak'
    | '/scenes/$scene'
    | '/scenes'
  id:
    | '__root__'
    | '/'
    | '/ai-room'
    | '/daily'
    | '/echo'
    | '/marathon'
    | '/progress'
    | '/scenes'
    | '/shadowing'
    | '/shorts'
    | '/sitemap.xml'
    | '/speak'
    | '/scenes/$scene'
    | '/scenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoomRoute: typeof AiRoomRoute
  DailyRoute: typeof DailyRoute
  EchoRoute: typeof EchoRoute
  MarathonRoute: typeof MarathonRoute
  ProgressRoute: typeof ProgressRoute
  ScenesRoute: typeof ScenesRouteWithChildren
  ShadowingRoute: typeof ShadowingRoute
  ShortsRoute: typeof ShortsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakRoute: typeof SpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing': {
      id: '/shadowing'
      path: '/shadowing'
      fullPath: '/shadowing'
      preLoaderRoute: typeof ShadowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathon': {
      id: '/marathon'
      path: '/marathon'
      fullPath: '/marathon'
      preLoaderRoute: typeof MarathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-room': {
      id: '/ai-room'
      path: '/ai-room'
      fullPath: '/ai-room'
      preLoaderRoute: typeof AiRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/': {
      id: '/scenes/'
      path: '/'
      fullPath: '/scenes/'
      preLoaderRoute: typeof ScenesIndexRouteImport
      parentRoute: typeof ScenesRoute
    }
    '/scenes/$scene': {
      id: '/scenes/$scene'
      path: '/$scene'
      fullPath: '/scenes/$scene'
      preLoaderRoute: typeof ScenesSceneRouteImport
      parentRoute: typeof ScenesRoute
    }
  }
}

interface ScenesRouteChildren {
  ScenesSceneRoute: typeof ScenesSceneRoute
  ScenesIndexRoute: typeof ScenesIndexRoute
}

const ScenesRouteChildren: ScenesRouteChildren = {
  ScenesSceneRoute: ScenesSceneRoute,
  ScenesIndexRoute: ScenesIndexRoute,
}

const ScenesRouteWithChildren =
  ScenesRoute._addFileChildren(ScenesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoomRoute: AiRoomRoute,
  DailyRoute: DailyRoute,
  EchoRoute: EchoRoute,
  MarathonRoute: MarathonRoute,
  ProgressRoute: ProgressRoute,
  ScenesRoute: ScenesRouteWithChildren,
  ShadowingRoute: ShadowingRoute,
  ShortsRoute: ShortsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakRoute: SpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
