/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RajaKitchenMenuRouteImport } from './routes/raja-kitchen-menu'
import { Route as IndianCuisineRouteImport } from './routes/indian-cuisine'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RajaKitchenMenuRoute = RajaKitchenMenuRouteImport.update({
  id: '/raja-kitchen-menu',
  path: '/raja-kitchen-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndianCuisineRoute = IndianCuisineRouteImport.update({
  id: '/indian-cuisine',
  path: '/indian-cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indian-cuisine': typeof IndianCuisineRoute
  '/raja-kitchen-menu': typeof RajaKitchenMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indian-cuisine': typeof IndianCuisineRoute
  '/raja-kitchen-menu': typeof RajaKitchenMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indian-cuisine': typeof IndianCuisineRoute
  '/raja-kitchen-menu': typeof RajaKitchenMenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indian-cuisine' | '/raja-kitchen-menu' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indian-cuisine' | '/raja-kitchen-menu' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/indian-cuisine'
    | '/raja-kitchen-menu'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndianCuisineRoute: typeof IndianCuisineRoute
  RajaKitchenMenuRoute: typeof RajaKitchenMenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raja-kitchen-menu': {
      id: '/raja-kitchen-menu'
      path: '/raja-kitchen-menu'
      fullPath: '/raja-kitchen-menu'
      preLoaderRoute: typeof RajaKitchenMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-cuisine': {
      id: '/indian-cuisine'
      path: '/indian-cuisine'
      fullPath: '/indian-cuisine'
      preLoaderRoute: typeof IndianCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndianCuisineRoute: IndianCuisineRoute,
  RajaKitchenMenuRoute: RajaKitchenMenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
