/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as MlopsRouteImport } from './routes/mlops'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const MlopsRoute = MlopsRouteImport.update({
  id: '/mlops',
  path: '/mlops',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/cloud': typeof CloudRoute
  '/knowledge': typeof KnowledgeRoute
  '/mlops': typeof MlopsRoute
  '/parents': typeof ParentsRoute
  '/traces': typeof TracesRoute
  '/transport': typeof TransportRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/cloud': typeof CloudRoute
  '/knowledge': typeof KnowledgeRoute
  '/mlops': typeof MlopsRoute
  '/parents': typeof ParentsRoute
  '/traces': typeof TracesRoute
  '/transport': typeof TransportRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/cloud': typeof CloudRoute
  '/knowledge': typeof KnowledgeRoute
  '/mlops': typeof MlopsRoute
  '/parents': typeof ParentsRoute
  '/traces': typeof TracesRoute
  '/transport': typeof TransportRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/attendance'
    | '/cloud'
    | '/knowledge'
    | '/mlops'
    | '/parents'
    | '/traces'
    | '/transport'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/attendance'
    | '/cloud'
    | '/knowledge'
    | '/mlops'
    | '/parents'
    | '/traces'
    | '/transport'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/attendance'
    | '/cloud'
    | '/knowledge'
    | '/mlops'
    | '/parents'
    | '/traces'
    | '/transport'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRoute
  CloudRoute: typeof CloudRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MlopsRoute: typeof MlopsRoute
  ParentsRoute: typeof ParentsRoute
  TracesRoute: typeof TracesRoute
  TransportRoute: typeof TransportRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mlops': {
      id: '/mlops'
      path: '/mlops'
      fullPath: '/mlops'
      preLoaderRoute: typeof MlopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRoute,
  CloudRoute: CloudRoute,
  KnowledgeRoute: KnowledgeRoute,
  MlopsRoute: MlopsRoute,
  ParentsRoute: ParentsRoute,
  TracesRoute: TracesRoute,
  TransportRoute: TransportRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
