import {
  BrainCircuit,
  Bot,
  Layers,
  Network,
  Languages,
  Sparkles,
  Cpu,
  Database,
  Table2,
  Send,
  Gamepad2,
  Target,
  RotateCw,
  TrendingDown,
  Scale,
  ArrowUpDown,
  Settings2,
  SlidersHorizontal,
  Compass,
  Zap,
  Shuffle,
  Puzzle,
  MapPin,
  Boxes,
  Search,
  Wrench,
  MessageSquareText,
  PlugZap,
  Plug,
  Webhook,
  History,
  Users,
  Rocket,
  Workflow,
  Waves,
  Radar,
  ScanSearch,
  Scissors,
  Landmark,
  Play,
  Thermometer,
  CircleSlash,
  CircleDot,
  PackageCheck,
  Shrink,
  Timer,
  CircuitBoard,
  FunctionSquare,
  ShieldCheck,
  UserCheck,
  GitMerge,
  ClipboardCheck,
  Activity,
  Shield,
  type LucideIcon,
} from "lucide-react";

export interface TermTile {
  term: string;
  icon: LucideIcon;
  short: string;
  why: string;
  example: string;
}

export const termTiles: TermTile[] = [
  {
    term: "Machine Learning (ML)",
    icon: BrainCircuit,
    short: "A branch of AI where computers learn patterns from data instead of following hard-coded rules.",
    why: "Learns from examples, allowing it to make predictions on new, unseen data.",
    example:
      "Train a model on thousands of spam and non-spam emails so it can classify new emails automatically.",
  },
  {
    term: "Artificial Intelligence (AI)",
    icon: Bot,
    short:
      "The field of creating systems that can perform tasks requiring human intelligence, such as learning, reasoning, and decision-making.",
    why: "Enables computers to solve complex problems and automate intelligent tasks.",
    example:
      "ChatGPT answering questions, Siri understanding voice commands, or a self-driving car recognizing traffic signs.",
  },
  {
    term: "Deep Learning (DL)",
    icon: Layers,
    short:
      "A subset of Machine Learning that uses neural networks with many layers to learn complex patterns from large amounts of data.",
    why: "Excels at solving problems involving images, speech, language, and other complex data.",
    example: "A facial recognition system learns to identify people by training on millions of images.",
  },
  {
    term: "Neural Network",
    icon: Network,
    short:
      "A Machine Learning model inspired by the human brain that learns patterns by connecting many simple processing units called neurons.",
    why: "Helps solve complex problems that are difficult to handle with traditional algorithms.",
    example:
      "A neural network learns to recognize handwritten digits by training on thousands of labeled images.",
  },
  {
    term: "Large Language Model (LLM)",
    icon: Languages,
    short: "An AI model trained on massive amounts of text to understand and generate human-like language.",
    why: "Powers applications that can answer questions, write content, summarize text, and assist with coding.",
    example: "ChatGPT uses a Large Language Model to answer questions, explain concepts, and generate code.",
  },
  {
    term: "Generative AI (GenAI)",
    icon: Sparkles,
    short:
      "A type of AI that creates new content such as text, images, audio, video, or code based on user prompts.",
    why: "Helps automate content creation, improve productivity, and assist with creative and technical tasks.",
    example: "ChatGPT generates text, DALL·E creates images, and GitHub Copilot writes code.",
  },
  {
    term: "Model",
    icon: Cpu,
    short: "A trained AI system that has learned patterns from data and can make predictions or generate outputs.",
    why: "The model is the \"brain\" that applies what it learned to solve new problems.",
    example: "A spam detection model predicts whether a new email is spam or not.",
  },
  {
    term: "Dataset",
    icon: Database,
    short: "A collection of data used to train, validate, or test an AI model.",
    why: "A well-prepared dataset helps the model learn accurate and reliable patterns.",
    example: "A CSV file containing customer age, income, and purchase history.",
  },
  {
    term: "Feature",
    icon: Table2,
    short: "An individual piece of information (input variable) used by a model to make predictions.",
    why: "Features provide the information the model uses to learn and make decisions.",
    example:
      "For predicting house prices, features could include the number of bedrooms, square footage, and location.",
  },
  {
    term: "Inference",
    icon: Send,
    short: "The process of using a trained AI model to make predictions or generate outputs on new data.",
    why: "Inference is when the model applies what it learned to solve real-world tasks.",
    example: "A trained spam filter classifies a newly received email as spam or not spam.",
  },
  {
    term: "Reinforcement Learning (RL)",
    icon: Gamepad2,
    short:
      "A type of Machine Learning where an agent learns by interacting with an environment and receiving rewards or penalties.",
    why: "Helps AI learn the best actions through trial and error.",
    example: "An AI learns to play chess by earning rewards for winning games and penalties for losing.",
  },
  {
    term: "Generalization",
    icon: Target,
    short: "A model's ability to perform well on new, unseen data after training.",
    why: "Good generalization is the ultimate goal of Machine Learning.",
    example: "A fraud detection model accurately identifies fraudulent transactions it has never encountered before.",
  },
  {
    term: "Epoch",
    icon: RotateCw,
    short: "One complete pass of the entire training dataset through the model during training.",
    why: "Multiple epochs help the model gradually improve its learning.",
    example: "If you train on 10,000 images once, you've completed 1 epoch.",
  },
  {
    term: "Gradient Descent",
    icon: TrendingDown,
    short: "An optimization algorithm that updates the model's parameters to minimize the loss function.",
    why: "Helps the model gradually find the best parameters for accurate predictions.",
    example: "After each training step, Gradient Descent adjusts the model's weights to reduce prediction errors.",
  },
  {
    term: "Weight",
    icon: Scale,
    short: "A numerical value the model learns during training that determines how important a feature is.",
    why: "Adjusting weights helps the model make more accurate predictions.",
    example: "In house price prediction, square footage may receive a higher weight than the paint color.",
  },
  {
    term: "Bias",
    icon: ArrowUpDown,
    short: "A learnable value added to the model that helps improve its predictions.",
    why: "Allows the model to fit data more accurately, even when all inputs are zero.",
    example: "A bias helps a prediction line shift up or down to better match the data.",
  },
  {
    term: "Hyperparameter",
    icon: Settings2,
    short: "A setting chosen before training that controls how the model learns.",
    why: "Hyperparameters affect the model's performance and training process.",
    example: "Learning rate, batch size, and the number of epochs are common hyperparameters.",
  },
  {
    term: "Parameter",
    icon: SlidersHorizontal,
    short: "A value learned by the model during training that is used to make predictions.",
    why: "Parameters capture the patterns the model learns from the data.",
    example: "The weights and biases inside a neural network are parameters.",
  },
  {
    term: "Optimizer",
    icon: Compass,
    short: "An algorithm that updates the model's parameters to reduce errors during training.",
    why: "Helps the model learn faster and reach better accuracy.",
    example: "Adam and SGD (Stochastic Gradient Descent) are popular optimizers.",
  },
  {
    term: "Activation Function",
    icon: Zap,
    short:
      "A mathematical function that decides whether a neuron should pass information to the next layer.",
    why: "Allows neural networks to learn complex, non-linear patterns.",
    example: "ReLU is one of the most commonly used activation functions in deep learning.",
  },
  {
    term: "Transformer",
    icon: Shuffle,
    short:
      "A deep learning architecture designed to understand relationships between words and sequences efficiently.",
    why: "It powers most modern Large Language Models because it handles long contexts and scales well.",
    example: "ChatGPT, Gemini, Claude, and Llama are all built using the Transformer architecture.",
  },
  {
    term: "Token",
    icon: Puzzle,
    short: "The smallest unit of text an AI model processes, such as a word, part of a word, or punctuation.",
    why: "LLMs read and generate text one token at a time.",
    example: 'The sentence "I love AI!" is split into multiple tokens before being processed.',
  },
  {
    term: "Embedding",
    icon: MapPin,
    short: "A numerical representation of text, images, or other data that captures their meaning.",
    why: "Helps AI compare similarity, search information, and retrieve relevant content.",
    example: 'The words "car" and "automobile" have similar embeddings because they have similar meanings.',
  },
  {
    term: "Vector Database",
    icon: Boxes,
    short: "A database designed to store and search embeddings efficiently.",
    why: "Enables AI applications to quickly find the most relevant information based on meaning rather than exact words.",
    example:
      "A RAG chatbot stores document embeddings in a vector database to retrieve relevant documents before answering a question.",
  },
  {
    term: "RAG (Retrieval-Augmented Generation)",
    icon: Search,
    short:
      "A technique where an AI model retrieves relevant information from external sources before generating a response.",
    why: "Helps the model provide more accurate, up-to-date, and context-aware answers.",
    example: "A company chatbot searches internal documents before answering an employee's question.",
  },
  {
    term: "Fine-Tuning",
    icon: Wrench,
    short: "The process of further training a pre-trained model on a specific dataset for a particular task.",
    why: "Improves the model's performance for a specific domain or use case.",
    example: "Fine-tuning an LLM on legal documents to build a legal assistant.",
  },
  {
    term: "Prompt Engineering",
    icon: MessageSquareText,
    short: "The practice of designing effective prompts to get better results from AI models.",
    why: "Well-crafted prompts improve the quality, accuracy, and consistency of AI responses.",
    example: 'Instead of asking "Explain AI," ask "Explain AI to a 10-year-old with a real-world example."',
  },
  {
    term: "Tool Calling",
    icon: PlugZap,
    short: "The ability of an AI model to use external tools, APIs, or applications to complete a task.",
    why: "Allows AI to perform actions beyond its built-in knowledge.",
    example: "An AI calls a weather API to provide today's forecast instead of guessing.",
  },
  {
    term: "MCP (Model Context Protocol)",
    icon: Plug,
    short:
      "A standard protocol that allows AI models to securely connect with external tools, data sources, and applications.",
    why: "Provides a consistent way for AI to access real-time information and perform actions.",
    example: "A coding assistant uses MCP to read GitHub repositories, search documentation, or query a database.",
  },
  {
    term: "Inference API",
    icon: Webhook,
    short: "An API that lets applications send inputs to a trained AI model and receive predictions or generated outputs.",
    why: "Makes it easy to use AI models without managing the underlying infrastructure.",
    example: "A web app sends a user's question to an LLM through an inference API and receives the answer.",
  },
  {
    term: "Memory",
    icon: History,
    short: "The ability of an AI system to retain and use information from previous interactions or stored data.",
    why: "Helps AI provide more personalized, consistent, and context-aware responses.",
    example: "An AI remembers your preferred programming language and uses it in future code examples.",
  },
  {
    term: "Multi-Agent System",
    icon: Users,
    short: "A system where multiple AI agents collaborate, each handling a specific role or responsibility.",
    why: "Improves efficiency by dividing complex tasks among specialized agents.",
    example: "One agent researches, another writes the report, and a third reviews it before delivery.",
  },
  {
    term: "AI Model Deployment",
    icon: Rocket,
    short: "The process of making a trained AI model available for real-world use.",
    why: "Allows users and applications to access the model through APIs or applications.",
    example: "Deploying a fraud detection model so a banking app can analyze every transaction.",
  },
  {
    term: "MLOps (Machine Learning Operations)",
    icon: Workflow,
    short: "The practice of managing, deploying, monitoring, and maintaining Machine Learning models in production.",
    why: "Ensures AI models remain reliable, scalable, and up to date after deployment.",
    example: "Automatically retraining a recommendation model when new customer data becomes available.",
  },
  {
    term: "Model Drift",
    icon: Waves,
    short: "When a model's performance decreases because real-world data changes over time.",
    why: "Detecting drift helps keep AI models accurate and reliable.",
    example: "A fraud detection model becomes less accurate as new fraud patterns emerge.",
  },
  {
    term: "Vector Search",
    icon: Radar,
    short: "A search technique that finds information based on meaning rather than exact keyword matches.",
    why: "Improves semantic search and powers RAG applications.",
    example:
      'Searching for "How do I reset my password?" also finds documents titled "Account Recovery" even without the exact words.',
  },
  {
    term: "Semantic Search",
    icon: ScanSearch,
    short: "A search technique that finds results based on meaning and context instead of exact keyword matches.",
    why: "Returns more relevant results, even when different words are used.",
    example: 'Searching for "How do I sign in?" also finds documents about "Login" or "Authentication."',
  },
  {
    term: "Tokenization",
    icon: Scissors,
    short: "The process of breaking text into smaller pieces called tokens before an AI model processes it.",
    why: "AI models understand and generate text one token at a time.",
    example: 'The sentence "AI is amazing!" is split into individual tokens before being processed.',
  },
  {
    term: "Foundation Model",
    icon: Landmark,
    short: "A large pre-trained AI model that serves as the base for many AI applications and specialized models.",
    why: "Reduces development time by providing broad knowledge that can be adapted to different tasks.",
    example: "GPT, Llama, Gemini, and Claude are foundation models used for chatbots, coding assistants, and content generation.",
  },
  {
    term: "AI Inference",
    icon: Play,
    short: "The process of using a trained AI model to generate predictions or responses from new input data.",
    why: "This is the stage where users actually interact with the AI model.",
    example: "Typing a prompt into ChatGPT and receiving an answer is AI inference.",
  },
  {
    term: "Temperature",
    icon: Thermometer,
    short: "A parameter that controls how random or creative an AI model's responses are.",
    why: "Helps balance predictable answers with creative generation.",
    example:
      "A low temperature gives factual, consistent answers, while a high temperature produces more creative responses.",
  },
  {
    term: "Zero-Shot Learning",
    icon: CircleSlash,
    short: "A technique where an AI model performs a task without seeing task-specific examples during training.",
    why: "Allows AI to handle new tasks using its existing knowledge.",
    example: "Ask an LLM to translate English to Telugu without providing translation examples.",
  },
  {
    term: "One-Shot Learning",
    icon: CircleDot,
    short: "A technique where an AI model learns a task from a single example provided in the prompt.",
    why: "Helps guide the model when one example is enough to show the expected format.",
    example: "Provide one input-output example before asking the model to solve a similar problem.",
  },
  {
    term: "Pre-trained Model",
    icon: PackageCheck,
    short: "A model that has already been trained on a large dataset and is ready to be used or fine-tuned.",
    why: "Saves significant time and computing resources compared to training from scratch.",
    example: "Using GPT or Llama as the starting point for building a customer support chatbot.",
  },
  {
    term: "Quantization",
    icon: Shrink,
    short: "A technique that reduces the size and memory usage of an AI model by using lower-precision numbers.",
    why: "Makes models faster, cheaper, and easier to run on laptops, phones, and edge devices.",
    example: "Converting a model from 32-bit to 8-bit precision to reduce memory usage.",
  },
  {
    term: "Latency",
    icon: Timer,
    short: "The time an AI model takes to generate a response after receiving a request.",
    why: "Lower latency provides a faster and better user experience.",
    example: "A chatbot replying in 1 second has lower latency than one taking 10 seconds.",
  },
  {
    term: "TPU (Tensor Processing Unit)",
    icon: CircuitBoard,
    short:
      "A specialized AI accelerator developed by Google for training and running Machine Learning models efficiently.",
    why: "Provides faster performance and better efficiency for large-scale AI workloads.",
    example: "Training a TensorFlow model on Google Cloud using TPUs instead of GPUs.",
  },
  {
    term: "Function Calling",
    icon: FunctionSquare,
    short: "A capability that allows an AI model to invoke predefined functions or APIs to perform specific actions.",
    why: "Enables AI to interact with external systems reliably and return structured results.",
    example: "A chatbot calls a getWeather() function instead of generating a weather forecast from memory.",
  },
  {
    term: "AI Hallucination Guardrails",
    icon: ShieldCheck,
    short: "Rules, validations, or external checks that reduce incorrect or misleading AI responses.",
    why: "Improves the reliability and safety of AI applications.",
    example: "A RAG system verifies answers using company documents before showing them to users.",
  },
  {
    term: "Human-in-the-Loop (HITL)",
    icon: UserCheck,
    short: "A workflow where a human reviews or approves an AI's decision before it is finalized.",
    why: "Adds oversight for important or high-risk tasks.",
    example: "An AI drafts a legal contract, but a lawyer must approve it before sending.",
  },
  {
    term: "Agent Orchestration",
    icon: GitMerge,
    short: "The process of coordinating multiple AI agents, tools, and workflows to complete a task efficiently.",
    why: "Ensures each agent performs the right task in the correct order.",
    example:
      "A planner agent assigns work to research, coding, and review agents, then combines their results into a final report.",
  },
  {
    term: "AI Evaluation (Eval)",
    icon: ClipboardCheck,
    short: "The process of testing an AI model or application to measure its quality, accuracy, and reliability.",
    why: "Ensures the AI performs as expected before and after deployment.",
    example: "Evaluating a chatbot by checking whether its answers are correct, relevant, and safe.",
  },
  {
    term: "AI Observability",
    icon: Activity,
    short: "The practice of monitoring AI models, agents, and workflows to understand their performance and behavior.",
    why: "Helps detect failures, latency issues, hallucinations, and performance degradation.",
    example: "A dashboard shows response time, token usage, tool calls, errors, and user feedback for an AI application.",
  },
  {
    term: "Guardrails",
    icon: Shield,
    short: "Rules and constraints that keep AI responses safe, accurate, and aligned with expected behavior.",
    why: "Prevents harmful, irrelevant, or incorrect outputs.",
    example: "An AI assistant refuses to generate malicious code or validates answers against company policies.",
  },
];
