/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as TimesTablesRouteImport } from './routes/times-tables'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as EasyTricksRouteImport } from './routes/easy-tricks'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as GradesIndexRouteImport } from './routes/grades.index'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'
import { Route as GradesGradeRouteImport } from './routes/grades.$grade'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesTablesRoute = TimesTablesRouteImport.update({
  id: '/times-tables',
  path: '/times-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const EasyTricksRoute = EasyTricksRouteImport.update({
  id: '/easy-tricks',
  path: '/easy-tricks',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsRoute,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GradesRoute,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => TopicsRoute,
} as any)
const GradesGradeRoute = GradesGradeRouteImport.update({
  id: '/$grade',
  path: '/$grade',
  getParentRoute: () => GradesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/easy-tricks': typeof EasyTricksRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/grades': typeof GradesRouteWithChildren
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRoute
  '/times-tables': typeof TimesTablesRoute
  '/tips': typeof TipsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/grades/$grade': typeof GradesGradeRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/grades/': typeof GradesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/easy-tricks': typeof EasyTricksRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRoute
  '/times-tables': typeof TimesTablesRoute
  '/tips': typeof TipsRoute
  '/grades/$grade': typeof GradesGradeRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/grades': typeof GradesIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/easy-tricks': typeof EasyTricksRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/grades': typeof GradesRouteWithChildren
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRoute
  '/times-tables': typeof TimesTablesRoute
  '/tips': typeof TipsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/grades/$grade': typeof GradesGradeRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/grades/': typeof GradesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/easy-tricks'
    | '/formulas'
    | '/games'
    | '/grades'
    | '/puzzles'
    | '/quiz'
    | '/times-tables'
    | '/tips'
    | '/topics'
    | '/grades/$grade'
    | '/topics/$topic'
    | '/grades/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictionary'
    | '/easy-tricks'
    | '/formulas'
    | '/games'
    | '/puzzles'
    | '/quiz'
    | '/times-tables'
    | '/tips'
    | '/grades/$grade'
    | '/topics/$topic'
    | '/grades'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/dictionary'
    | '/easy-tricks'
    | '/formulas'
    | '/games'
    | '/grades'
    | '/puzzles'
    | '/quiz'
    | '/times-tables'
    | '/tips'
    | '/topics'
    | '/grades/$grade'
    | '/topics/$topic'
    | '/grades/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionaryRoute: typeof DictionaryRoute
  EasyTricksRoute: typeof EasyTricksRoute
  FormulasRoute: typeof FormulasRoute
  GamesRoute: typeof GamesRoute
  GradesRoute: typeof GradesRouteWithChildren
  PuzzlesRoute: typeof PuzzlesRoute
  QuizRoute: typeof QuizRoute
  TimesTablesRoute: typeof TimesTablesRoute
  TipsRoute: typeof TipsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times-tables': {
      id: '/times-tables'
      path: '/times-tables'
      fullPath: '/times-tables'
      preLoaderRoute: typeof TimesTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easy-tricks': {
      id: '/easy-tricks'
      path: '/easy-tricks'
      fullPath: '/easy-tricks'
      preLoaderRoute: typeof EasyTricksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/grades/': {
      id: '/grades/'
      path: '/'
      fullPath: '/grades/'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof GradesRoute
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/grades/$grade': {
      id: '/grades/$grade'
      path: '/$grade'
      fullPath: '/grades/$grade'
      preLoaderRoute: typeof GradesGradeRouteImport
      parentRoute: typeof GradesRoute
    }
  }
}

interface GradesRouteChildren {
  GradesGradeRoute: typeof GradesGradeRoute
  GradesIndexRoute: typeof GradesIndexRoute
}

const GradesRouteChildren: GradesRouteChildren = {
  GradesGradeRoute: GradesGradeRoute,
  GradesIndexRoute: GradesIndexRoute,
}

const GradesRouteWithChildren =
  GradesRoute._addFileChildren(GradesRouteChildren)

interface TopicsRouteChildren {
  TopicsTopicRoute: typeof TopicsTopicRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsTopicRoute: TopicsTopicRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionaryRoute: DictionaryRoute,
  EasyTricksRoute: EasyTricksRoute,
  FormulasRoute: FormulasRoute,
  GamesRoute: GamesRoute,
  GradesRoute: GradesRouteWithChildren,
  PuzzlesRoute: PuzzlesRoute,
  QuizRoute: QuizRoute,
  TimesTablesRoute: TimesTablesRoute,
  TipsRoute: TipsRoute,
  TopicsRoute: TopicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
