/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TextRouteImport } from './routes/text'
import { Route as PicsRouteImport } from './routes/pics'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const PicsRoute = PicsRouteImport.update({
  id: '/pics',
  path: '/pics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pics': typeof PicsRoute
  '/text': typeof TextRoute
  '/videos': typeof VideosRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pics': typeof PicsRoute
  '/text': typeof TextRoute
  '/videos': typeof VideosRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pics': typeof PicsRoute
  '/text': typeof TextRoute
  '/videos': typeof VideosRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pics' | '/text' | '/videos' | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pics' | '/text' | '/videos' | '/voice'
  id: '__root__' | '/' | '/pics' | '/text' | '/videos' | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PicsRoute: typeof PicsRoute
  TextRoute: typeof TextRoute
  VideosRoute: typeof VideosRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pics': {
      id: '/pics'
      path: '/pics'
      fullPath: '/pics'
      preLoaderRoute: typeof PicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PicsRoute: PicsRoute,
  TextRoute: TextRoute,
  VideosRoute: VideosRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
