/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsingRouteImport } from './routes/using'
import { Route as ToBePublishedRouteImport } from './routes/to-be-published'
import { Route as MoneyReadyRouteImport } from './routes/money-ready'
import { Route as JustForMeRouteImport } from './routes/just-for-me'
import { Route as ControlCenterRouteImport } from './routes/control-center'
import { Route as IndexRouteImport } from './routes/index'

const UsingRoute = UsingRouteImport.update({
  id: '/using',
  path: '/using',
  getParentRoute: () => rootRouteImport,
} as any)
const ToBePublishedRoute = ToBePublishedRouteImport.update({
  id: '/to-be-published',
  path: '/to-be-published',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyReadyRoute = MoneyReadyRouteImport.update({
  id: '/money-ready',
  path: '/money-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const JustForMeRoute = JustForMeRouteImport.update({
  id: '/just-for-me',
  path: '/just-for-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRoute = ControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/just-for-me': typeof JustForMeRoute
  '/money-ready': typeof MoneyReadyRoute
  '/to-be-published': typeof ToBePublishedRoute
  '/using': typeof UsingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/just-for-me': typeof JustForMeRoute
  '/money-ready': typeof MoneyReadyRoute
  '/to-be-published': typeof ToBePublishedRoute
  '/using': typeof UsingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/just-for-me': typeof JustForMeRoute
  '/money-ready': typeof MoneyReadyRoute
  '/to-be-published': typeof ToBePublishedRoute
  '/using': typeof UsingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control-center'
    | '/just-for-me'
    | '/money-ready'
    | '/to-be-published'
    | '/using'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control-center'
    | '/just-for-me'
    | '/money-ready'
    | '/to-be-published'
    | '/using'
  id:
    | '__root__'
    | '/'
    | '/control-center'
    | '/just-for-me'
    | '/money-ready'
    | '/to-be-published'
    | '/using'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlCenterRoute: typeof ControlCenterRoute
  JustForMeRoute: typeof JustForMeRoute
  MoneyReadyRoute: typeof MoneyReadyRoute
  ToBePublishedRoute: typeof ToBePublishedRoute
  UsingRoute: typeof UsingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/using': {
      id: '/using'
      path: '/using'
      fullPath: '/using'
      preLoaderRoute: typeof UsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-be-published': {
      id: '/to-be-published'
      path: '/to-be-published'
      fullPath: '/to-be-published'
      preLoaderRoute: typeof ToBePublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-ready': {
      id: '/money-ready'
      path: '/money-ready'
      fullPath: '/money-ready'
      preLoaderRoute: typeof MoneyReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/just-for-me': {
      id: '/just-for-me'
      path: '/just-for-me'
      fullPath: '/just-for-me'
      preLoaderRoute: typeof JustForMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center': {
      id: '/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof ControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlCenterRoute: ControlCenterRoute,
  JustForMeRoute: JustForMeRoute,
  MoneyReadyRoute: MoneyReadyRoute,
  ToBePublishedRoute: ToBePublishedRoute,
  UsingRoute: UsingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
